### ISSUE TITLE
Add me!

### ISSUE THREAD

**Issue by Rookabu** [CSBiology/csbiology.github.io#18]
### **Name**

Annika Paul

### **Picture**

![Annika_Bild](https://github.com/CSBiology/csbiology.github.io/assets/160484408/edd2941f-6c93-4cc6-82c8-f71f98e2377d)

### **Role**:
Bachelor

### **GitHub**:

Rookabu

### **ORCID**

0009-0008-7417-0965

### **Email**

paula@rptu.de

**Comment by Freymaurer** [comment]
Done!
